import { MarketCapCategoryEnum } from './marketCaps';

export enum FundCategoryEnum {
  EQUITY = 'EQUITY',
  DEBT = 'DEBT',
  HYBRID = 'HYBRID',
  COMMODITIES = 'COMMODITIES',
}

export const marketCapCatId = {
  [MarketCapCategoryEnum.LARGE_CAP]: '100',
  [MarketCapCategoryEnum.LARGE_MID_CAP]: '101',
  [MarketCapCategoryEnum.FLEXI_CAP]: '102',
  [MarketCapCategoryEnum.MID_CAP]: '103',
  [MarketCapCategoryEnum.SMALL_CAP]: '104',
  [MarketCapCategoryEnum.VALUE_ORIENTED]: '105',
  [MarketCapCategoryEnum.ELSS]: '106',
  [MarketCapCategoryEnum.SECTORAL_BANKING]: '107',
  [MarketCapCategoryEnum.SECTORAL_FMCG]: '108',
  [MarketCapCategoryEnum.THEMATIC_INFRASTRUCTURE]: '109',
  [MarketCapCategoryEnum.SECTORAL_PHARMA]: '110',
  [MarketCapCategoryEnum.SECTORAL_TECHNOLOGY]: '111',
  [MarketCapCategoryEnum.THEMATIC]: '112',
  [MarketCapCategoryEnum.THEMATIC_DIVIDEND_YIELD]: '113',
  [MarketCapCategoryEnum.THEMATIC_MNC]: '114',
  [MarketCapCategoryEnum.THEMATIC_ENERGY]: '115',
  [MarketCapCategoryEnum.THEMATIC_PSU]: '116',
  [MarketCapCategoryEnum.THEMATIC_CONSUMPTION]: '117',
  [MarketCapCategoryEnum.INTERNATIONAL]: '118',
  [MarketCapCategoryEnum.LONG_DURATION]: '119',
  [MarketCapCategoryEnum.MEDIUM_TO_LONG_DURATION]: '120',
  [MarketCapCategoryEnum.MEDIUM_DURATION]: '121',
  [MarketCapCategoryEnum.SHORT_DURATION]: '122',
  [MarketCapCategoryEnum.LOW_DURATION]: '123',
  [MarketCapCategoryEnum.ULTRA_SHORT_DURATION]: '124',
  [MarketCapCategoryEnum.LIQUID]: '125',
  [MarketCapCategoryEnum.MONEY_MARKET]: '126',
  [MarketCapCategoryEnum.OVERNIGHT]: '127',
  [MarketCapCategoryEnum.DYNAMIC_BOND]: '128',
  [MarketCapCategoryEnum.CORPORATE_BOND]: '129',
  [MarketCapCategoryEnum.CREDIT_RISK]: '130',
  [MarketCapCategoryEnum.BANKING_AND_PSU]: '131',
  [MarketCapCategoryEnum.FLOATER]: '132',
  [MarketCapCategoryEnum.FIXED_MATURITY]: '133',
  [MarketCapCategoryEnum.GILT]: '134',
  [MarketCapCategoryEnum.GILT_10_YEAR_CONSTANT]: '135',
  [MarketCapCategoryEnum.HYBRID_AGGRESSIVE]: '136',
  [MarketCapCategoryEnum.HYBRID_BALANCED]: '137',
  [MarketCapCategoryEnum.HYBRID_BALANCED_ADVANTAGE]: '138',
  [MarketCapCategoryEnum.HYBRID_CONSERVATIVE]: '139',
  [MarketCapCategoryEnum.HYBRID_EQUITY_SAVINGS]: '140',
  [MarketCapCategoryEnum.HYBRID_ARBITRAGE]: '141',
  [MarketCapCategoryEnum.HYBRID_DYNAMIC_ASSET_ALLOCATION]: '142',
  [MarketCapCategoryEnum.HYBRID_MULTI_ASSET_ALLOCATION]: '143',
  [MarketCapCategoryEnum.GOLD]: '144',
  [MarketCapCategoryEnum.MULTI_CAP]: '145',
  [MarketCapCategoryEnum.THEMATIC_ESG]: '146',
  [MarketCapCategoryEnum.SILVER]: '147',
  [MarketCapCategoryEnum.TARGET_MATURITY]: '148',
  [MarketCapCategoryEnum.DEBT_OTHERS]: '149',
  [MarketCapCategoryEnum.HYBRID_INCOME_PLUS_ARBITRAGE]: '150',
  [MarketCapCategoryEnum.SECTORAL_AUTO_TRANSPORTATION]: '151',
  [MarketCapCategoryEnum.THEMATIC_BUSINESS_CYCLE]: '152',
  [MarketCapCategoryEnum.THEMATIC_INNOVATION]: '153',
  [MarketCapCategoryEnum.THEMATIC_MANUFACTURING]: '154',
  [MarketCapCategoryEnum.THEMATIC_QUANT]: '155',
} as const;

export const marketCapByFundCategory = Object.freeze({
  [FundCategoryEnum.EQUITY]: Object.freeze([
    marketCapCatId.LARGE_CAP,
    marketCapCatId.LARGE_MID_CAP,
    marketCapCatId.FLEXI_CAP,
    marketCapCatId.MID_CAP,
    marketCapCatId.SMALL_CAP,
    marketCapCatId.MULTI_CAP,
    marketCapCatId.VALUE_ORIENTED,
    marketCapCatId.ELSS,
    marketCapCatId.SECTORAL_BANKING,
    marketCapCatId.SECTORAL_FMCG,
    marketCapCatId.SECTORAL_PHARMA,
    marketCapCatId.SECTORAL_TECHNOLOGY,
    marketCapCatId.SECTORAL_AUTO_TRANSPORTATION,
    marketCapCatId.THEMATIC,
    marketCapCatId.THEMATIC_DIVIDEND_YIELD,
    marketCapCatId.THEMATIC_MNC,
    marketCapCatId.THEMATIC_ENERGY,
    marketCapCatId.THEMATIC_PSU,
    marketCapCatId.THEMATIC_CONSUMPTION,
    marketCapCatId.THEMATIC_INFRASTRUCTURE,
    marketCapCatId.THEMATIC_ESG,
    marketCapCatId.THEMATIC_BUSINESS_CYCLE,
    marketCapCatId.THEMATIC_INNOVATION,
    marketCapCatId.THEMATIC_MANUFACTURING,
    marketCapCatId.THEMATIC_QUANT,
    marketCapCatId.INTERNATIONAL,
  ]),
  [FundCategoryEnum.DEBT]: Object.freeze([
    marketCapCatId.LONG_DURATION,
    marketCapCatId.MEDIUM_TO_LONG_DURATION,
    marketCapCatId.MEDIUM_DURATION,
    marketCapCatId.SHORT_DURATION,
    marketCapCatId.LOW_DURATION,
    marketCapCatId.ULTRA_SHORT_DURATION,
    marketCapCatId.LIQUID,
    marketCapCatId.MONEY_MARKET,
    marketCapCatId.OVERNIGHT,
    marketCapCatId.DYNAMIC_BOND,
    marketCapCatId.CORPORATE_BOND,
    marketCapCatId.CREDIT_RISK,
    marketCapCatId.BANKING_AND_PSU,
    marketCapCatId.FLOATER,
    marketCapCatId.FIXED_MATURITY,
    marketCapCatId.GILT,
    marketCapCatId.GILT_10_YEAR_CONSTANT,
    marketCapCatId.TARGET_MATURITY,
    marketCapCatId.DEBT_OTHERS,
  ]),
  [FundCategoryEnum.HYBRID]: Object.freeze([
    marketCapCatId.HYBRID_AGGRESSIVE,
    marketCapCatId.HYBRID_BALANCED,
    marketCapCatId.HYBRID_BALANCED_ADVANTAGE,
    marketCapCatId.HYBRID_CONSERVATIVE,
    marketCapCatId.HYBRID_EQUITY_SAVINGS,
    marketCapCatId.HYBRID_ARBITRAGE,
    marketCapCatId.HYBRID_DYNAMIC_ASSET_ALLOCATION,
    marketCapCatId.HYBRID_MULTI_ASSET_ALLOCATION,
    marketCapCatId.HYBRID_INCOME_PLUS_ARBITRAGE,
  ]),
  [FundCategoryEnum.COMMODITIES]: Object.freeze([
    marketCapCatId.GOLD,
    marketCapCatId.SILVER,
  ]),
} as const);

export const marketCapBySubCategoryValue: Readonly<
  Partial<Record<MarketCapCategoryEnum, readonly string[]>>
> = Object.freeze({
  [MarketCapCategoryEnum.FLEXI_CAP]: Object.freeze([
    marketCapCatId.FLEXI_CAP,
  ]),
  [MarketCapCategoryEnum.INTERNATIONAL]: Object.freeze([
    marketCapCatId.INTERNATIONAL,
  ]),
  [MarketCapCategoryEnum.LARGE_MID_CAP]: Object.freeze([
    marketCapCatId.LARGE_MID_CAP,
  ]),
  [MarketCapCategoryEnum.LARGE_CAP]: Object.freeze([marketCapCatId.LARGE_CAP]),
  [MarketCapCategoryEnum.MID_CAP]: Object.freeze([marketCapCatId.MID_CAP]),
  [MarketCapCategoryEnum.MULTI_CAP]: Object.freeze([
    marketCapCatId.MULTI_CAP,
  ]),
  [MarketCapCategoryEnum.SECTORAL]: Object.freeze([
    marketCapCatId.SECTORAL_BANKING,
    marketCapCatId.SECTORAL_FMCG,
    marketCapCatId.SECTORAL_PHARMA,
    marketCapCatId.SECTORAL_TECHNOLOGY,
    marketCapCatId.SECTORAL_AUTO_TRANSPORTATION,
  ]),
  [MarketCapCategoryEnum.SMALL_CAP]: Object.freeze([marketCapCatId.SMALL_CAP]),
  [MarketCapCategoryEnum.ELSS]: Object.freeze([marketCapCatId.ELSS]),
  [MarketCapCategoryEnum.THEMATIC]: Object.freeze([
    marketCapCatId.THEMATIC,
    marketCapCatId.THEMATIC_DIVIDEND_YIELD,
    marketCapCatId.THEMATIC_MNC,
    marketCapCatId.THEMATIC_ENERGY,
    marketCapCatId.THEMATIC_PSU,
    marketCapCatId.THEMATIC_CONSUMPTION,
    marketCapCatId.THEMATIC_INFRASTRUCTURE,
    marketCapCatId.THEMATIC_ESG,
    marketCapCatId.THEMATIC_BUSINESS_CYCLE,
    marketCapCatId.THEMATIC_INNOVATION,
    marketCapCatId.THEMATIC_MANUFACTURING,
    marketCapCatId.THEMATIC_QUANT,
  ]),
  [MarketCapCategoryEnum.VALUE_ORIENTED]: Object.freeze([
    marketCapCatId.VALUE_ORIENTED,
  ]),
  [MarketCapCategoryEnum.BANKING_AND_PSU]: Object.freeze([
    marketCapCatId.BANKING_AND_PSU,
  ]),
  [MarketCapCategoryEnum.CORPORATE_BOND]: Object.freeze([
    marketCapCatId.CORPORATE_BOND,
  ]),
  [MarketCapCategoryEnum.CREDIT_RISK]: Object.freeze([
    marketCapCatId.CREDIT_RISK,
  ]),
  [MarketCapCategoryEnum.DYNAMIC_BOND]: Object.freeze([
    marketCapCatId.DYNAMIC_BOND,
  ]),
  [MarketCapCategoryEnum.FIXED_MATURITY]: Object.freeze([
    marketCapCatId.FIXED_MATURITY,
  ]),
  [MarketCapCategoryEnum.FLOATER]: Object.freeze([marketCapCatId.FLOATER]),
  [MarketCapCategoryEnum.GILT]: Object.freeze([marketCapCatId.GILT]),
  [MarketCapCategoryEnum.GILT_10_YEAR_CONSTANT]: Object.freeze([
    marketCapCatId.GILT_10_YEAR_CONSTANT,
  ]),
  [MarketCapCategoryEnum.LIQUID]: Object.freeze([marketCapCatId.LIQUID]),
  [MarketCapCategoryEnum.LONG_DURATION]: Object.freeze([
    marketCapCatId.LONG_DURATION,
  ]),
  [MarketCapCategoryEnum.LOW_DURATION]: Object.freeze([marketCapCatId.LOW_DURATION]),
  [MarketCapCategoryEnum.MEDIUM_DURATION]: Object.freeze([
    marketCapCatId.MEDIUM_DURATION,
  ]),
  [MarketCapCategoryEnum.MEDIUM_TO_LONG_DURATION]: Object.freeze([
    marketCapCatId.MEDIUM_TO_LONG_DURATION,
  ]),
  [MarketCapCategoryEnum.MONEY_MARKET]: Object.freeze([
    marketCapCatId.MONEY_MARKET,
  ]),
  [MarketCapCategoryEnum.OVERNIGHT]: Object.freeze([marketCapCatId.OVERNIGHT]),
  [MarketCapCategoryEnum.SHORT_DURATION]: Object.freeze([
    marketCapCatId.SHORT_DURATION,
  ]),
  [MarketCapCategoryEnum.TARGET_MATURITY]: Object.freeze([
    marketCapCatId.TARGET_MATURITY,
  ]),
  [MarketCapCategoryEnum.ULTRA_SHORT_DURATION]: Object.freeze([
    marketCapCatId.ULTRA_SHORT_DURATION,
  ]),
  [MarketCapCategoryEnum.HYBRID_AGGRESSIVE]: Object.freeze([
    marketCapCatId.HYBRID_AGGRESSIVE,
  ]),
  [MarketCapCategoryEnum.HYBRID_ARBITRAGE]: Object.freeze([
    marketCapCatId.HYBRID_ARBITRAGE,
  ]),
  [MarketCapCategoryEnum.HYBRID_BALANCED]: Object.freeze([
    marketCapCatId.HYBRID_BALANCED,
  ]),
  [MarketCapCategoryEnum.HYBRID_CONSERVATIVE]: Object.freeze([
    marketCapCatId.HYBRID_CONSERVATIVE,
  ]),
  [MarketCapCategoryEnum.HYBRID_DYNAMIC_ASSET_ALLOCATION]: Object.freeze([
    marketCapCatId.HYBRID_DYNAMIC_ASSET_ALLOCATION,
  ]),
  [MarketCapCategoryEnum.HYBRID_EQUITY_SAVINGS]: Object.freeze([
    marketCapCatId.HYBRID_EQUITY_SAVINGS,
  ]),
  [MarketCapCategoryEnum.HYBRID_MULTI_ASSET_ALLOCATION]: Object.freeze([
    marketCapCatId.HYBRID_MULTI_ASSET_ALLOCATION,
  ]),
  [MarketCapCategoryEnum.GOLD]: Object.freeze([marketCapCatId.GOLD]),
  [MarketCapCategoryEnum.SILVER]: Object.freeze([marketCapCatId.SILVER]),
} as const);