export enum MarketCapCategoryEnum {
  // Equity - Core
  LARGE_CAP = 'LARGE_CAP',
  LARGE_MID_CAP = 'LARGE_MID_CAP',
  FLEXI_CAP = 'FLEXI_CAP',
  MID_CAP = 'MID_CAP',
  SMALL_CAP = 'SMALL_CAP',
  MULTI_CAP = 'MULTI_CAP',
  VALUE_ORIENTED = 'VALUE_ORIENTED',

  // Equity - ELSS
  ELSS = 'ELSS',

  // Equity - Sectoral
  SECTORAL_BANKING = 'SECTORAL_BANKING',
  SECTORAL_FMCG = 'SECTORAL_FMCG',
  SECTORAL_PHARMA = 'SECTORAL_PHARMA',
  SECTORAL_TECHNOLOGY = 'SECTORAL_TECHNOLOGY',
  SECTORAL_AUTO_TRANSPORTATION = 'SECTORAL_AUTO_TRANSPORTATION',

  // Equity - Thematic
  THEMATIC = 'THEMATIC',
  THEMATIC_DIVIDEND_YIELD = 'THEMATIC_DIVIDEND_YIELD',
  THEMATIC_MNC = 'THEMATIC_MNC',
  THEMATIC_ENERGY = 'THEMATIC_ENERGY',
  THEMATIC_PSU = 'THEMATIC_PSU',
  THEMATIC_CONSUMPTION = 'THEMATIC_CONSUMPTION',
  THEMATIC_INFRASTRUCTURE = 'THEMATIC_INFRASTRUCTURE',
  THEMATIC_ESG = 'THEMATIC_ESG',
  THEMATIC_BUSINESS_CYCLE = 'THEMATIC_BUSINESS_CYCLE',
  THEMATIC_INNOVATION = 'THEMATIC_INNOVATION',
  THEMATIC_MANUFACTURING = 'THEMATIC_MANUFACTURING',
  THEMATIC_QUANT = 'THEMATIC_QUANT',

  // Equity - International
  INTERNATIONAL = 'INTERNATIONAL',

  // Debt - Duration Based
  LONG_DURATION = 'LONG_DURATION',
  MEDIUM_TO_LONG_DURATION = 'MEDIUM_TO_LONG_DURATION',
  MEDIUM_DURATION = 'MEDIUM_DURATION',
  SHORT_DURATION = 'SHORT_DURATION',
  LOW_DURATION = 'LOW_DURATION',
  ULTRA_SHORT_DURATION = 'ULTRA_SHORT_DURATION',

  // Debt - Short Term
  LIQUID = 'LIQUID',
  MONEY_MARKET = 'MONEY_MARKET',
  OVERNIGHT = 'OVERNIGHT',

  // Debt - Bond Types
  DYNAMIC_BOND = 'DYNAMIC_BOND',
  CORPORATE_BOND = 'CORPORATE_BOND',
  CREDIT_RISK = 'CREDIT_RISK',
  BANKING_AND_PSU = 'BANKING_AND_PSU',
  FLOATER = 'FLOATER',
  FIXED_MATURITY = 'FIXED_MATURITY',
  GILT = 'GILT',
  GILT_10_YEAR_CONSTANT = 'GILT_10_YEAR_CONSTANT',

  // Debt - Other
  TARGET_MATURITY = 'TARGET_MATURITY',
  DEBT_OTHERS = 'DEBT_OTHERS',

  // Hybrid - Standard
  HYBRID_AGGRESSIVE = 'HYBRID_AGGRESSIVE',
  HYBRID_BALANCED = 'HYBRID_BALANCED',
  HYBRID_CONSERVATIVE = 'HYBRID_CONSERVATIVE',

  // Hybrid - Special
  HYBRID_EQUITY_SAVINGS = 'HYBRID_EQUITY_SAVINGS',
  HYBRID_ARBITRAGE = 'HYBRID_ARBITRAGE',
  HYBRID_DYNAMIC_ASSET_ALLOCATION = 'HYBRID_DYNAMIC_ASSET_ALLOCATION',
  HYBRID_MULTI_ASSET_ALLOCATION = 'HYBRID_MULTI_ASSET_ALLOCATION',
  HYBRID_BALANCED_ADVANTAGE = 'HYBRID_BALANCED_ADVANTAGE',
  HYBRID_INCOME_PLUS_ARBITRAGE = 'HYBRID_INCOME_PLUS_ARBITRAGE',

  // Commodities
  GOLD = 'GOLD',
  SILVER = 'SILVER',

  //general categories
  SECTORAL = 'SECTORAL',
}

export enum RiskProfileEnum {
  LOW = 'LOW',
  MODERATELY_LOW = 'MODERATELY_LOW',
  MODERATE = 'MODERATE',
  MODERATELY_HIGH = 'MODERATELY_HIGH',
  HIGH = 'HIGH',
  VERY_HIGH = 'VERY_HIGH',
}
