export const errorCodes = {
  LEAD_NOT_FOUND: 'LEAD_NOT_FOUND',
  DOB_NOT_ELIGIBLE: 'DOB_NOT_ELIGIBLE',
  INVALID_ORG_TYPE: 'INVALID_ORG_TYPE',
  INVALID_SALARY: 'INVALID_SALARY',
  INVALID_SALARY_RANGE: 'INVALID_SALARY_RANGE',
  INVALID_FOIR_PERCENTAGE: 'INVALID_FOIR_PERCENTAGE',
  INVALID_EXPECTED_AMOUNT: 'INVALID_EXPECTED_AMOUNT',
  UCC_PROFILE_NOT_COMPLETE: 'UCC_PROFILE_NOT_COMPLETE',
  LUMPSUM_NOT_ALLOWED: 'LUMPSUM_NOT_ALLOWED',
  PURCHASE_PERIOD_EXPIRED: 'PURCHASE_PERIOD_EXPIRED',
  PURCHASE_NOT_ALLOWED: 'PURCHASE_NOT_ALLOWED',
  INVALID_INVESTMENT_MODE: 'INVALID_INVESTMENT_MODE',

  // Goal
  GOAL_NOT_FOUND: 'GOAL_NOT_FOUND',
  GOAL_NOT_DRAFT: 'GOAL_NOT_DRAFT',
  GOAL_HAS_SIP: 'GOAL_HAS_SIP',
  GOAL_HAS_ORDER: 'GOAL_HAS_ORDER',
  GOAL_NOT_GROUP: 'GOAL_NOT_GROUP',
  GOAL_NO_GROUP_ID: 'GOAL_NO_GROUP_ID',
  GOAL_HAS_MEMBERS: 'GOAL_HAS_MEMBERS',
  GOAL_NOT_CREATOR: 'GOAL_NOT_CREATOR',
  GROUP_HAS_INVESTED_MEMBERS: 'GROUP_HAS_INVESTED_MEMBERS',
  INVESTMENT_GOAL_NOT_FOUND: 'INVESTMENT_GOAL_NOT_FOUND',
  SIP_DATA_NOT_FOUND: 'SIP_DATA_NOT_FOUND',
  ORDER_DATA_NOT_FOUND: 'ORDER_DATA_NOT_FOUND',
  GOAL_ALREADY_LEFT: 'GOAL_ALREADY_LEFT',

  // 2FA
  UNSUPPORTED_2FA_EVENT: 'UNSUPPORTED_2FA_EVENT',
  UCC_NOT_FOUND: 'UCC_NOT_FOUND',
  GOAL_LINKED_TO_ACTIVE_SIP: 'GOAL_LINKED_TO_ACTIVE_SIP',
  INVESTMENT_GOAL_MISSING: 'INVESTMENT_GOAL_MISSING',

  // Fixerra
  FIXERRA_ERROR: 'FIXERRA_ERROR',
  FIXERRA_API_TIMEOUT: 'FIXERRA_API_TIMEOUT',
  FIXERRA_API_UNAVAILABLE: 'FIXERRA_API_UNAVAILABLE',
  FIXERRA_USER_NOT_REGISTERED: 'FIXERRA_USER_NOT_REGISTERED',
  FIXERRA_AUTH_CODE_MISSING: 'FIXERRA_AUTH_CODE_MISSING',
  FIXERRA_AUTH_CODE_EXPIRED: 'FIXERRA_AUTH_CODE_EXPIRED',
  FIXERRA_GET_REDIRECTION_FAILED: 'FIXERRA_GET_REDIRECTION_FAILED',
};
