export const errorCodes = {
  LEAD_NOT_FOUND: 'LEAD_NOT_FOUND',
  DOB_NOT_ELIGIBLE: 'DOB_NOT_ELIGIBLE',
  INVALID_ORG_TYPE: 'INVALID_ORG_TYPE',
  INVALID_SALARY: 'INVALID_SALARY',
  INVALID_SALARY_RANGE: 'INVALID_SALARY_RANGE',
  INVALID_FOIR_PERCENTAGE: 'INVALID_FOIR_PERCENTAGE',
  INVALID_EXPECTED_AMOUNT: 'INVALID_EXPECTED_AMOUNT',
  UCC_PROFILE_NOT_COMPLETE: 'UCC_PROFILE_NOT_COMPLETE',
  LUMPSUM_NOT_ALLOWED: 'LUMPSUM_NOT_ALLOWED',
  PURCHASE_PERIOD_EXPIRED: 'PURCHASE_PERIOD_EXPIRED',
  PURCHASE_NOT_ALLOWED: 'PURCHASE_NOT_ALLOWED',
  INVALID_INVESTMENT_MODE: 'INVALID_INVESTMENT_MODE',

  // Consent
  CONSENT_REQUIRED: 'CONSENT_REQUIRED',

  // Goal
  GOAL_NOT_FOUND: 'GOAL_NOT_FOUND',
  GOAL_NOT_DRAFT: 'GOAL_NOT_DRAFT',
  GOAL_HAS_SIP: 'GOAL_HAS_SIP',
  GOAL_HAS_ORDER: 'GOAL_HAS_ORDER',
  GOAL_NOT_GROUP: 'GOAL_NOT_GROUP',
  GOAL_NO_GROUP_ID: 'GOAL_NO_GROUP_ID',
  GOAL_HAS_MEMBERS: 'GOAL_HAS_MEMBERS',
  GOAL_NOT_CREATOR: 'GOAL_NOT_CREATOR',
  GROUP_HAS_INVESTED_MEMBERS: 'GROUP_HAS_INVESTED_MEMBERS',
  INVESTMENT_GOAL_NOT_FOUND: 'INVESTMENT_GOAL_NOT_FOUND',
  SIP_DATA_NOT_FOUND: 'SIP_DATA_NOT_FOUND',
  ORDER_DATA_NOT_FOUND: 'ORDER_DATA_NOT_FOUND',
  GOAL_ALREADY_LEFT: 'GOAL_ALREADY_LEFT',

  // Order
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_NOT_FOUND_OR_NOT_CANCELABLE: 'ORDER_NOT_FOUND_OR_NOT_CANCELABLE',
  ORDER_NOT_CANCELABLE: 'ORDER_NOT_CANCELABLE',
  ORDER_PLACEMENT_FAILED: 'ORDER_PLACEMENT_FAILED',
  ORDER_CANCELLATION_NOT_ALLOWED: 'ORDER_CANCELLATION_NOT_ALLOWED',
  LUMPSUM_ORDER_CANCEL_FAILED: 'LUMPSUM_ORDER_CANCEL_FAILED',

  // 2FA
  UNSUPPORTED_2FA_EVENT: 'UNSUPPORTED_2FA_EVENT',
  UCC_NOT_FOUND: 'UCC_NOT_FOUND',
  GOAL_LINKED_TO_ACTIVE_SIP: 'GOAL_LINKED_TO_ACTIVE_SIP',
  INVESTMENT_GOAL_MISSING: 'INVESTMENT_GOAL_MISSING',

  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // Fixerra
  FIXERRA_ERROR: 'FIXERRA_ERROR',
  FIXERRA_REGISTER_USER_FAILED: 'FIXERRA_REGISTER_USER_FAILED',
  FIXERRA_AUTH_CODE_FAILED: 'FIXERRA_AUTH_CODE_FAILED',
  FIXERRA_API_TIMEOUT: 'FIXERRA_API_TIMEOUT',
  FIXERRA_API_UNAVAILABLE: 'FIXERRA_API_UNAVAILABLE',
  FIXERRA_USER_NOT_REGISTERED: 'FIXERRA_USER_NOT_REGISTERED',
  FIXERRA_AUTH_CODE_MISSING: 'FIXERRA_AUTH_CODE_MISSING',
  FIXERRA_AUTH_CODE_EXPIRED: 'FIXERRA_AUTH_CODE_EXPIRED',
  FIXERRA_GET_REDIRECTION_FAILED: 'FIXERRA_GET_REDIRECTION_FAILED',
  // Group game
  GAME_MIN_MEMBERS: 'GAME_MIN_MEMBERS', // fewer than GROUP_GAME_MIN_MEMBERS active members
  GAME_NOT_ELIGIBLE: 'GAME_NOT_ELIGIBLE', // group has not crossed the coin gate
  GAME_INVALID_TEAM_SIZE: 'GAME_INVALID_TEAM_SIZE', // not a proper divisor of the active member count
  GAME_LOCKED: 'GAME_LOCKED', // a score exists; mode/game can no longer change
  GAME_NOT_STARTED: 'GAME_NOT_STARTED', // creator has not selected a mode and game yet
  GAME_NOT_OPEN: 'GAME_NOT_OPEN', // round closed or tournament finished
  GAME_NOT_PARTICIPANT: 'GAME_NOT_PARTICIPANT', // requesting user is not in the current round
  GAME_NO_TRIES_LEFT: 'GAME_NO_TRIES_LEFT', // all tries used in this round
  // Weekly contest between circles
  CONTEST_NOT_FOUND: 'CONTEST_NOT_FOUND',
  CONTEST_NOT_QUALIFIED: 'CONTEST_NOT_QUALIFIED', // circle has not reached CONTEST_QUALIFY_COINS
  CONTEST_MIN_MEMBERS: 'CONTEST_MIN_MEMBERS', // fewer than CONTEST_MIN_MEMBERS active members
  CONTEST_NOT_CREATOR: 'CONTEST_NOT_CREATOR', // only the circle creator can register or cancel
  CONTEST_REGISTRATION_CLOSED: 'CONTEST_REGISTRATION_CLOSED', // outside Monday 00:00 – Friday 23:59:59 IST
  CONTEST_INVALID_TEAM_COUNT: 'CONTEST_INVALID_TEAM_COUNT', // not in contestTeamOptions(activeMembers)
  CONTEST_NOT_REGISTERED: 'CONTEST_NOT_REGISTERED', // nothing to cancel
  CONTEST_NOT_LIVE: 'CONTEST_NOT_LIVE', // tries can only start on Saturday of a LIVE contest
  CONTEST_NOT_TEAM_MEMBER: 'CONTEST_NOT_TEAM_MEMBER', // requesting user is not on that team
  CONTEST_NO_TRIES_LEFT: 'CONTEST_NO_TRIES_LEFT', // the team used all its tries
  CONTEST_TRY_NOT_FOUND: 'CONTEST_TRY_NOT_FOUND', // unknown try, or started by someone else
  CONTEST_TRY_ALREADY_SUBMITTED: 'CONTEST_TRY_ALREADY_SUBMITTED', // a try's score can be sent once
  CONTEST_SUBMIT_TOO_LATE: 'CONTEST_SUBMIT_TOO_LATE', // after submitGraceEndsAt
};
