import { z } from 'zod';
import { InvestmentGoalType } from './goalType';
import { UserSchema } from './auth';

export enum InvestmentGoalStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export const InvestmentGoalSchema = z.object({
  id: z.string(), // Optional because it's generated by backend during POST
  type: z.nativeEnum(InvestmentGoalType),
  name: z.string().optional(),
  targetAmt: z.number().optional(),
  targetDate: z.coerce.date().optional(),
  description: z.string().optional(),
  userId: z.string(),
  user: UserSchema.optional(),
  investedAmt: z.number(),
  sipInstallment: z.number(),
  status: z.nativeEnum(InvestmentGoalStatus),
});

export const NewInvestmentGoalSchema = InvestmentGoalSchema.omit({
  id: true, // Exclude id from new goals since backend generates it
  userId: true,
  user: true,
  investedAmt: true,
  sipInstallment: true,
  status: true,
});

export const UpdateInvestmentGoalSchema = InvestmentGoalSchema.partial()
  .omit({
    type: true,
    userId: true,
    user: true,
  })
  .strict();

export type NewInvestmentGoal = z.infer<typeof NewInvestmentGoalSchema>;
export type UpdateInvestmentGoal = z.infer<typeof UpdateInvestmentGoalSchema>;
export type InvestmentGoal = z.infer<typeof InvestmentGoalSchema>;

// --- Goal list response types ---

/** Group-level aggregated investment summary returned inside a GoalListItem */
export const GoalListItemGroupInvestmentSchema = z.object({
  communityGoalGroupId:      z.string(),
  groupName:                z.string(),
  totalInvestedByGroup:     z.number(), // Decimal — do not use as Float
  groupTargetAmt:           z.number(), // Decimal — sum of all active members' targetAmt
  groupCompletionPercentage: z.number(), // 0–100, rounded to 2 dp
});

/** Lightweight goal summary returned by the getAllGoals list endpoint */
export const GoalListItemSchema = z.object({
  id:                   z.string(),
  type:                 z.string(),
  targetAmt:            z.number().nullable(),  // Decimal
  investedAmt:          z.number().nullable(),  // Decimal
  goalType:             z.enum(['INDIVIDUAL_GOAL', 'GROUP_GOAL']),
  name:                 z.string().nullable(),
  completionPercentage: z.number(),             // 0–100, computed
  groupInvestment:      GoalListItemGroupInvestmentSchema.nullable(),
});

export type GoalListItemGroupInvestment = z.infer<typeof GoalListItemGroupInvestmentSchema>;
export type GoalListItem = z.infer<typeof GoalListItemSchema>;
