import { z } from 'zod';
import { InvestmentGoalType } from './goalType';
import { UserSchema } from './auth';

export enum InvestmentGoalStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export const InvestmentGoalSchema = z.object({
  id: z.string(), // Optional because it's generated by backend during POST
  type: z.nativeEnum(InvestmentGoalType),
  name: z.string().optional(),
  targetAmt: z.number().optional(),
  targetDate: z.coerce.date().optional(),
  description: z.string().optional(),
  userId: z.string(),
  user: UserSchema.optional(),
  investedAmt: z.number(),
  sipInstallment: z.number(),
  status: z.nativeEnum(InvestmentGoalStatus),
});

export const NewInvestmentGoalSchema = InvestmentGoalSchema.omit({
  id: true, // Exclude id from new goals since backend generates it
  userId: true,
  user: true,
  investedAmt: true,
  sipInstallment: true,
  status: true,
});

export const UpdateInvestmentGoalSchema = InvestmentGoalSchema.partial()
  .omit({
    type: true,
    userId: true,
    user: true,
  })
  .strict();

export type NewInvestmentGoal = z.infer<typeof NewInvestmentGoalSchema>;
export type UpdateInvestmentGoal = z.infer<typeof UpdateInvestmentGoalSchema>;
export type InvestmentGoal = z.infer<typeof InvestmentGoalSchema>;

// --- Goal list response types ---

/** Group-level aggregated investment summary returned inside a GoalListItem */
export const GoalListItemGroupInvestmentSchema = z.object({
  communityGoalGroupId: z.string(),
  groupName: z.string(),
  totalInvestedByGroup: z.number(), // Decimal — do not use as Float
  groupTargetAmt: z.number(), // Decimal — sum of all active members' targetAmt
  groupCompletionPercentage: z.number(), // 0–100, rounded to 2 dp
});

/** Lightweight goal summary returned by the getAllGoals list endpoint */
export const GoalListItemSchema = z.object({
  id: z.string(),
  type: z.string(),
  targetAmt: z.number().nullable(), // Decimal
  investedAmt: z.number().nullable(), // Decimal
  goalType: z.enum(['INDIVIDUAL_GOAL', 'GROUP_GOAL']),
  name: z.string().nullable(),
  completionPercentage: z.number(), // 0–100, computed
  groupInvestment: GoalListItemGroupInvestmentSchema.nullable(),
});

export type GoalListItemGroupInvestment = z.infer<
  typeof GoalListItemGroupInvestmentSchema
>;
export type GoalListItem = z.infer<typeof GoalListItemSchema>;

/** MF / market-linked investment breakdown — includes day-1 return metrics. */
export const InvestmentBreakdownSchema = z.object({
  totalHolding: z.number().int(), // Count of individual holdings (schemes / instruments)
  totalInvestedAmount: z.number(),
  currentValue: z.number(),
  returns: z.object({
    day1ReturnValue: z.number(),
    day1ReturnPercentage: z.number(),
    totalReturnValue: z.number(),
    totalReturnPercentage: z.number(),
  }),
});

/** Mutual-funds-specific breakdown — extends base with XIRR. */
export const MutualFundsBreakdownSchema = InvestmentBreakdownSchema.extend({
  xirr: z.number(), // Annualised internal rate of return (XIRR) for the MF portfolio
});

/**
 * Bank-deposit breakdown (FD / RD).
 * No day-1 return — interest accrues over the deposit tenure, not daily.
 */
export const BankDepositBreakdownSchema = z.object({
  totalHolding: z.number().int(), // Count of individual deposit accounts (FD / RD)
  investedAmt: z.number(), // Total principal deposited
  accruedValue: z.number(), // Principal + interest accrued to date
  interestEarned: z.number(), // Interest earned so far
  effectiveYield: z.number(), // Annualised effective yield (%)
});

export const NetworthDetailsSchema = z.object({
  mutualFunds: MutualFundsBreakdownSchema,
  bankDeposits: BankDepositBreakdownSchema,
  /** Aggregated breakdown combining mutualFunds + bankDeposits. combined.currentValue is the total networth. */
  combined: InvestmentBreakdownSchema,
});

export type InvestmentBreakdown = z.infer<typeof InvestmentBreakdownSchema>;
export type MutualFundsBreakdown = z.infer<typeof MutualFundsBreakdownSchema>;
export type BankDepositBreakdown = z.infer<typeof BankDepositBreakdownSchema>;
export type NetworthDetails = z.infer<typeof NetworthDetailsSchema>;

/** Full investment goal record returned by getMutualFundsInvestment (SIP or lumpsum, API status success). */
export const MutualFundsInvestmentItemSchema = z.object({
  id: z.string(),
  type: z.string(),
  targetAmt: z.number().nullable(),
  targetDate: z.coerce.date().nullable(),
  investedAmt: z.number().nullable(),
  status: z.string(),
  goalType: z.enum(['INDIVIDUAL_GOAL', 'GROUP_GOAL']),
  orderId: z.string().nullable(),
  orderStatus: z.string().nullable(),
  sipId: z.string().nullable(),
  sipStatus: z.string().nullable(),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
  investmentType: z.enum(['SIP', 'LUMPSUM', 'UNKNOWN']),
  schemeName: z.string().nullable(),
});

export type MutualFundsInvestmentItem = z.infer<typeof MutualFundsInvestmentItemSchema>;
